steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/256702831943/altcoin-screener', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/256702831943/altcoin-screener']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'altcoin-screener'
    - '--image'
    - 'gcr.io/256702831943/altcoin-screener'
    - '--region'
    - 'asia-east1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'PYTHONUNBUFFERED=1,RATE_LIMIT_SECONDS=1,API_TIMEOUT_SECONDS=10,MAX_RETRIES=3,LOG_LEVEL=INFO'
    - '--set-secrets'
    - 'BINANCE_API_KEY=BINANCE_API_KEY:latest,BINANCE_SECRET_KEY=BINANCE_SECRET_KEY:latest,TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest'

images:
  - 'gcr.io/256702831943/altcoin-screener'