# Fly.io App Configuration File
app = "alt-anomalies"
primary_region = "otp"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "python alt-anomalies.py"

[mounts]
  source = "data"
  destination = "/app/data"

[checks]
  [checks.http]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"
